"""Pure functions that turn a Jupyter notebook (as JSON) into a chat dialog — no JupyterLab, no OpenAI required.

Docs: https://Jack-Byte.github.io/yasidialog.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dialog.ipynb.

# %% auto #0
__all__ = ['tag_in_cell', 'cell_roles', 'multiple_tags_warning', 'extract_dialog']

# %% ../nbs/01_dialog.ipynb #ac171be8
def tag_in_cell(cell, # Dictonary of a Jupyter Notebook cell
                tag # The tag to search
               )->bool: # True if any line contains the given tag
    """Checks a Jupyter Notebook cells source, if any line starts with the given tag"""
    return any([line.startswith(tag) for line in cell['source']])

# %% ../nbs/01_dialog.ipynb #bd7b09b7
def cell_roles(cell, # Dictonary of a Jupyter Notebook cell
               tags:dict # Mapping of role name to tag, e.g. {'user': '#| chat_user'}
              )->list: # Roles whose tag was found in the cell
    """Returns all dialog roles whose tag appears in the given cell"""
    return [role for role, tag in tags.items() if tag_in_cell(cell, tag)]

# %% ../nbs/01_dialog.ipynb #b018cb4d
def multiple_tags_warning(cell # Dictonary of a Jupyter Notebook cell
                         )->str: # Markdown warning text
    """Builds the warning text for a cell that contains more than one dialog tag"""
    tmp_content = '## \u26a0\u26a0\u26a0 cell contains multiple tags \u26a0\u26a0\u26a0\n'
    tmp_content += 'identify the following cell and select only one tag\n'
    tmp_content += '> ' + '> '.join(cell['source'])
    return tmp_content

# %% ../nbs/01_dialog.ipynb #fdb62d4c
def extract_dialog(notebook:dict, # Jupyter Notebook JSON as a dictionary
                   tag_system:str='#| chat_system', # tag for system chat markdown cells
                   tag_user:str='#| chat_user', # tag for user chat markdown cells
                   tag_assistant:str='#| chat_assistant' # tag for assistant chat markdown cells
                  )->tuple: # (messages, warnings)
    """Extracts the tagged dialog from a notebook dictionary and turns it into a messages list.
    Returns the messages plus warning texts for cells containing multiple tags."""
    tags = {'system': tag_system, 'user': tag_user, 'assistant': tag_assistant}
    messages, warnings = [], []
    for cell in notebook['cells']:
        roles = cell_roles(cell, tags)
        if len(roles) == 1:
            messages.append({"role": roles[0], "content": ''.join(cell['source'])})
        if len(roles) > 1:
            warnings.append(multiple_tags_warning(cell))
    return messages, warnings
