"""Thin wrapper around an OpenAI-compatible chat completions API. Knows nothing about notebooks or JupyterLab.

Docs: https://Jack-Byte.github.io/yasiclient.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_client.ipynb.

# %% auto #0
__all__ = ['ANTHROPIC_DEFAULT_MAX_TOKENS', 'model_entry', 'prepare_params', 'usage_totals', 'estimate_cost', 'format_usage',
           'ChatClient']

# %% ../nbs/02_client.ipynb #0bd3b130
def model_entry(model # A model object as returned by `client.models.list()`
               )->dict: # dict with keys company/name/id
    """Builds yasi's model dict from an API model object, tolerating provider-specific fields
    (OpenRouter: `name`, OpenAI: `owned_by`, Anthropic: `display_name`)"""
    name = getattr(model, 'name', None)
    display_name = getattr(model, 'display_name', None)
    owned_by = getattr(model, 'owned_by', None)
    if name: company = name.split(':')[0]
    elif owned_by: company = owned_by
    elif '/' in model.id: company = model.id.split('/')[0]
    else: company = model.id.split('-')[0]
    return {"company": company,
            "name": name if name else (display_name if display_name else model.id.split('/')[-1]),
            "id": model.id,
            "pricing": getattr(model, 'pricing', None)}

# %% ../nbs/02_client.ipynb #d4c04ab1
ANTHROPIC_DEFAULT_MAX_TOKENS = 4096

def prepare_params(base_url, # base url of the api, used to detect the provider
                   model:str=None,
                   max_tokens:int=None,
                   temperature:float=None,
                   presence_penalty:float=None
                  )->dict: # keyword arguments for `chat.completions.create`
    """Adjusts request parameters to provider quirks (currently: Anthropic's temperature range,
    required max_tokens and unsupported presence_penalty)"""
    if 'anthropic' in str(base_url or ''):
        if temperature is not None: temperature = max(0.0, min(temperature, 1.0))
        if max_tokens is None: max_tokens = ANTHROPIC_DEFAULT_MAX_TOKENS
        presence_penalty = None
    return dict(model=model, max_tokens=max_tokens,
                temperature=temperature, presence_penalty=presence_penalty)

# %% ../nbs/02_client.ipynb #396ee448
def usage_totals(usage_log:list # List of usage dicts with prompt_tokens/completion_tokens
                )->dict: # Totals over the whole log
    """Sums token usage over a usage log"""
    pt = sum(u['prompt_tokens'] for u in usage_log)
    ct = sum(u['completion_tokens'] for u in usage_log)
    return {'prompt_tokens': pt, 'completion_tokens': ct, 'total_tokens': pt + ct}

def estimate_cost(usage_log:list, # List of usage dicts with model/prompt_tokens/completion_tokens
                  models:list # Model dicts as returned by `get_models` (with 'pricing')
                 ): # Estimated cost in USD, or None if no pricing information is available
    """Estimates spend from per-token pricing where available (e.g. OpenRouter)"""
    pricing_by_id = {m['id']: m.get('pricing') for m in (models or [])}
    cost, known = 0.0, False
    for u in usage_log:
        pricing = pricing_by_id.get(u.get('model'))
        if pricing and pricing.get('prompt') is not None:
            cost += u['prompt_tokens'] * float(pricing['prompt'])
            cost += u['completion_tokens'] * float(pricing.get('completion') or 0)
            known = True
    return cost if known else None

def format_usage(usage_log:list, # List of usage dicts
                 models:list=None # Model dicts, for cost estimation
                )->str: # One-line summary for display
    """Formats the last exchange and running totals (plus cost, if estimable) as one line"""
    if not usage_log: return ''
    last, totals = usage_log[-1], usage_totals(usage_log)
    text = (f"Last: {last['prompt_tokens']}\u2191 {last['completion_tokens']}\u2193 | "
            f"Total: {totals['prompt_tokens']}\u2191 {totals['completion_tokens']}\u2193 tokens")
    cost = estimate_cost(usage_log, models)
    if cost is not None:
        text += f" (~${cost:.4f})"
    return text

# %% ../nbs/02_client.ipynb #674aebbe
import openai

class ChatClient:
    """Wraps an `openai.Client` for listing models and sending chat completions."""
    def __init__(self,
                 api_key : str=None,  # api key for the openai api
                 openai_base_url : str=None # base url of the openai api
                ):
        self.client = openai.Client(base_url=openai_base_url, api_key=api_key)
        self.latest_response = None
        self.usage_log = []

    def get_models(self):
        """Create list of model objects from the Openai client"""
        return [model_entry(model) for model in self.client.models.list()]

    def _log_usage(self, model, usage):
        if usage is not None:
            self.usage_log.append({'model': model,
                                   'prompt_tokens': getattr(usage, 'prompt_tokens', 0) or 0,
                                   'completion_tokens': getattr(usage, 'completion_tokens', 0) or 0})

    def chat(self,
             messages: list, # A list of messages comprising the conversation so far.
             model: str=None, # model id for the openai api
             max_tokens: int=None,
             temperature: float=None,
             presence_penalty: float=None,
             stream: bool=False, # stream the response
             on_chunk=None # callback(text_so_far), called after every streamed chunk
            )->str: # The response text, or an error description
        """Send messages a.k.a dialog to the Openai chat completions API"""
        params = prepare_params(self.client.base_url,
                                model=model,
                                max_tokens=max_tokens,
                                temperature=temperature,
                                presence_penalty=presence_penalty)
        try:
            if stream:
                response_text, usage = '', None
                chunks = self.client.chat.completions.create(messages=messages, stream=True,
                                                             stream_options={'include_usage': True}, **params)
                for chunk in chunks:
                    self.latest_response = chunk
                    if getattr(chunk, 'usage', None) is not None:
                        usage = chunk.usage
                    if chunk.choices and getattr(chunk.choices[0].delta, 'content', None):
                        response_text += chunk.choices[0].delta.content
                        if on_chunk is not None:
                            on_chunk(response_text)
                self._log_usage(model, usage)
                response_text = response_text.strip()
            else:
                response = self.client.chat.completions.create(messages=messages, **params)
                self.latest_response = response
                self._log_usage(model, getattr(response, 'usage', None))
                response_text = response.choices[0].message.content.strip()
        except Exception as e:
            response_text = f'There was an problem communicating with the Openai API:\n\n{e}'
        return response_text
