"""Thin wrapper around an OpenAI-compatible chat completions API. Knows nothing about notebooks or JupyterLab.

Docs: https://Jack-Byte.github.io/yasiclient.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_client.ipynb.

# %% auto #0
__all__ = ['ANTHROPIC_DEFAULT_MAX_TOKENS', 'model_entry', 'prepare_params', 'ChatClient']

# %% ../nbs/02_client.ipynb #3078e4aa
def model_entry(model # A model object as returned by `client.models.list()`
               )->dict: # dict with keys company/name/id
    """Builds yasi's model dict from an API model object, tolerating provider-specific fields
    (OpenRouter: `name`, OpenAI: `owned_by`, Anthropic: `display_name`)"""
    name = getattr(model, 'name', None)
    display_name = getattr(model, 'display_name', None)
    owned_by = getattr(model, 'owned_by', None)
    if name: company = name.split(':')[0]
    elif owned_by: company = owned_by
    elif '/' in model.id: company = model.id.split('/')[0]
    else: company = model.id.split('-')[0]
    return {"company": company,
            "name": name if name else (display_name if display_name else model.id.split('/')[-1]),
            "id": model.id}

# %% ../nbs/02_client.ipynb #dbe1e62b
ANTHROPIC_DEFAULT_MAX_TOKENS = 4096

def prepare_params(base_url, # base url of the api, used to detect the provider
                   model:str=None,
                   max_tokens:int=None,
                   temperature:float=None,
                   presence_penalty:float=None
                  )->dict: # keyword arguments for `chat.completions.create`
    """Adjusts request parameters to provider quirks (currently: Anthropic's temperature range,
    required max_tokens and unsupported presence_penalty)"""
    if 'anthropic' in str(base_url or ''):
        if temperature is not None: temperature = max(0.0, min(temperature, 1.0))
        if max_tokens is None: max_tokens = ANTHROPIC_DEFAULT_MAX_TOKENS
        presence_penalty = None
    return dict(model=model, max_tokens=max_tokens,
                temperature=temperature, presence_penalty=presence_penalty)

# %% ../nbs/02_client.ipynb #674aebbe
import openai

class ChatClient:
    """Wraps an `openai.Client` for listing models and sending chat completions."""
    def __init__(self,
                 api_key : str=None,  # api key for the openai api
                 openai_base_url : str=None # base url of the openai api
                ):
        self.client = openai.Client(base_url=openai_base_url, api_key=api_key)
        self.latest_response = None

    def get_models(self):
        """Create list of model objects from the Openai client"""
        return [model_entry(model) for model in self.client.models.list()]

    def chat(self,
             messages: list, # A list of messages comprising the conversation so far.
             model: str=None, # model id for the openai api
             max_tokens: int=None,
             temperature: float=None,
             presence_penalty: float=None
            )->str: # The response text, or an error description
        """Send messages a.k.a dialog to the Openai chat completions API"""
        params = prepare_params(self.client.base_url,
                                model=model,
                                max_tokens=max_tokens,
                                temperature=temperature,
                                presence_penalty=presence_penalty)
        try:
            response = self.client.chat.completions.create(messages=messages, **params)
            self.latest_response = response
            response_text = response.choices[0].message.content.strip()
        except Exception as e:
            response_text = f'There was an problem communicating with the Openai API:\n\n{e}'
        return response_text
