"""Pure functions that turn a Jupyter notebook (as JSON) into a chat dialog — no JupyterLab, no OpenAI required.

Docs: https://Jack-Byte.github.io/yasidialog.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dialog.ipynb.

# %% auto #0
__all__ = ['PROMPT_MAGIC', 'tag_in_cell', 'cell_roles', 'strip_ansi', 'render_output', 'render_outputs', 'code_cell_content',
           'is_prompt_cell', 'prompt_body', 'notebook_upto_prompt', 'multiple_tags_warning', 'extract_dialog']

# %% ../nbs/01_dialog.ipynb #2fb904d9
def tag_in_cell(cell, # Dictonary of a Jupyter Notebook cell
                tag # The tag to search
               )->bool: # True if any line contains the given tag
    """Checks a Jupyter Notebook cells source, if any line starts with the given tag"""
    return any([line.startswith(tag) for line in cell['source']])

# %% ../nbs/01_dialog.ipynb #3084b1df
def cell_roles(cell, # Dictonary of a Jupyter Notebook cell
               tags:dict # Mapping of role name to tag, e.g. {'user': '#| chat_user'}
              )->list: # Roles whose tag was found in the cell
    """Returns all dialog roles whose tag appears in the given cell"""
    return [role for role, tag in tags.items() if tag_in_cell(cell, tag)]

# %% ../nbs/01_dialog.ipynb #64320b42
import re

_ANSI_RE = re.compile(r'\x1b\[[0-9;]*[a-zA-Z]')

def strip_ansi(text:str # Text possibly containing ANSI escape sequences
              )->str: # Text without ANSI escape sequences
    """Removes ANSI escape sequences (e.g. colors in tracebacks) from text"""
    return _ANSI_RE.sub('', text)

# %% ../nbs/01_dialog.ipynb #8fd72ff3
def render_output(output:dict, # A single entry of a code cell's 'outputs' list
                  skip_note:str='[non-text output skipped]' # Placeholder for non-text data
                 )->str: # Plain text representation
    """Renders one code cell output as plain text"""
    output_type = output.get('output_type')
    if output_type == 'stream':
        return ''.join(output.get('text', []))
    if output_type in ('execute_result', 'display_data'):
        data = output.get('data', {})
        if 'text/plain' in data: return ''.join(data['text/plain'])
        return skip_note
    if output_type == 'error':
        return strip_ansi('\n'.join(output.get('traceback', [])))
    return ''

def render_outputs(outputs:list, # A code cell's 'outputs' list
                   max_len:int=2000 # Maximum number of characters, longer output is truncated
                  )->str: # Plain text representation of all outputs
    """Renders all outputs of a code cell as plain text, truncated to `max_len` characters"""
    rendered = '\n'.join([r for r in (render_output(o) for o in outputs) if r.strip()])
    if max_len is not None and len(rendered) > max_len:
        rendered = rendered[:max_len] + '\n... [output truncated]'
    return rendered.strip()

# %% ../nbs/01_dialog.ipynb #81b455b0
def code_cell_content(cell:dict, # Dictonary of a Jupyter Notebook code cell
                      max_output_len:int=2000 # Maximum characters of rendered output
                     )->str: # Markdown-formatted message content
    """Turns a code cell into message content: fenced source plus rendered outputs"""
    content = f"```python\n{''.join(cell['source'])}\n```"
    rendered = render_outputs(cell.get('outputs', []), max_len=max_output_len)
    if rendered:
        content += f"\n\nOutput:\n```\n{rendered}\n```"
    return content

# %% ../nbs/01_dialog.ipynb #5ed057b8
PROMPT_MAGIC = '%%prompt'

def is_prompt_cell(cell:dict # Dictonary of a Jupyter Notebook cell
                  )->bool: # True if the cell is a code cell starting with the %%prompt magic
    """Checks whether a cell is a yasi prompt cell"""
    if cell['cell_type'] != 'code': return False
    return ''.join(cell['source']).lstrip().startswith(PROMPT_MAGIC)

def prompt_body(cell:dict # Dictonary of a Jupyter Notebook prompt cell
               )->str: # The prompt text without the magic line
    """Returns the source of a prompt cell without the leading %%prompt line"""
    lines = ''.join(cell['source']).lstrip().split('\n')
    return '\n'.join(lines[1:]).strip()

def notebook_upto_prompt(notebook:dict, # Jupyter Notebook JSON as a dictionary
                         body:str # Body of the currently executing prompt cell
                        )->tuple: # (truncated notebook dict, found flag)
    """Truncates the notebook after the first prompt cell whose body matches `body`"""
    cells, found = [], False
    for cell in notebook['cells']:
        cells.append(cell)
        if is_prompt_cell(cell) and prompt_body(cell) == body.strip():
            found = True
            break
    return {'cells': cells}, found

# %% ../nbs/01_dialog.ipynb #bd8768ba
def multiple_tags_warning(cell # Dictonary of a Jupyter Notebook cell
                         )->str: # Markdown warning text
    """Builds the warning text for a cell that contains more than one dialog tag"""
    tmp_content = '## \u26a0\u26a0\u26a0 cell contains multiple tags \u26a0\u26a0\u26a0\n'
    tmp_content += 'identify the following cell and select only one tag\n'
    tmp_content += '> ' + '> '.join(cell['source'])
    return tmp_content

# %% ../nbs/01_dialog.ipynb #62974a65
def extract_dialog(notebook:dict, # Jupyter Notebook JSON as a dictionary
                   tag_system:str='#| chat_system', # tag for system chat markdown cells
                   tag_user:str='#| chat_user', # tag for user chat markdown cells
                   tag_assistant:str='#| chat_assistant', # tag for assistant chat markdown cells
                   all_cells:bool=True, # send untagged markdown/code cells as user messages
                   max_output_len:int=2000 # maximum characters of rendered output per code cell
                  )->tuple: # (messages, warnings)
    """Extracts the dialog from a notebook dictionary and turns it into a messages list.
    Returns the messages plus warning texts for cells containing multiple tags."""
    tags = {'system': tag_system, 'user': tag_user, 'assistant': tag_assistant}
    messages, warnings = [], []
    for cell in notebook['cells']:
        roles = cell_roles(cell, tags)
        if len(roles) > 1:
            warnings.append(multiple_tags_warning(cell))
            continue
        source = ''.join(cell['source'])
        if len(roles) == 1:
            messages.append({"role": roles[0], "content": source})
            continue
        if not all_cells or not source.strip():
            continue
        if is_prompt_cell(cell):
            messages.append({"role": "user", "content": prompt_body(cell)})
        elif cell['cell_type'] == 'code':
            messages.append({"role": "user", "content": code_cell_content(cell, max_output_len=max_output_len)})
        elif cell['cell_type'] == 'markdown':
            messages.append({"role": "user", "content": source})
    return messages, warnings
