"""The `%%prompt` cell magic: solveit-style prompt cells for plain Jupyter. Running a prompt cell sends everything *above* it (using `yasi.dialog.extract_dialog`) plus the prompt itself, and inserts the tagged response as a new markdown cell below.

Docs: https://Jack-Byte.github.io/yasimagics.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_magics.ipynb.

# %% auto #0
__all__ = ['YasiMagics', 'load_prompt_magic']

# %% ../nbs/04_magics.ipynb #98a7e49a
from IPython.core.magic import Magics, magics_class, cell_magic

from .dialog import extract_dialog, notebook_upto_prompt

@magics_class
class YasiMagics(Magics):
    """Registers the %%prompt cell magic, bound to a `JupyterChat` instance."""
    def __init__(self, shell, jc):
        super().__init__(shell)
        self.jc = jc

    @cell_magic
    def prompt(self, line, cell):
        """Send the dialog up to (and including) this prompt cell, insert the response below"""
        jc = self.jc
        notebook = jc.get_current_nb()
        notebook, found = notebook_upto_prompt(notebook, cell)
        messages, warnings = extract_dialog(notebook,
                                            tag_system=jc.tag_system,
                                            tag_user=jc.tag_user,
                                            tag_assistant=jc.tag_assistant,
                                            all_cells=jc.all_cells,
                                            max_output_len=jc.max_output_len)
        for warning in warnings:
            jc.create_new_markdown_cell(warning)
        if not found:
            # unsaved or edited prompt cell: still send the prompt itself
            messages.append({"role": "user", "content": cell.strip()})
        response_text = jc.chat_client.chat(messages,
                                            model=jc.model,
                                            max_tokens=jc.max_tokens,
                                            temperature=jc.temperature,
                                            presence_penalty=jc.presence_penalty)
        jc.latest_response = jc.chat_client.latest_response
        jc.create_new_markdown_cell(f"{jc.tag_assistant}\n\n{response_text.strip()}")

def load_prompt_magic(jc, # A JupyterChat instance the magic sends dialogs with
                      shell=None # IPython shell, defaults to the running one
                     ):
    """Registers the %%prompt magic in the running IPython shell"""
    if shell is None:
        from IPython import get_ipython
        shell = get_ipython()
    if shell is not None:
        shell.register_magics(YasiMagics(shell, jc))
